spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://codelitt.cbw30we97wnu.us-east-1.rds.amazonaws.com:5432/codelitt
    username: postgres
    password: pwd_9317_awd
    # JPA properties
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  messages:
    basename: messages

server:
  error:
    include-stacktrace: on_param